import pandas as pd
df=pd.read_csv('3/Iris.csv')
#df.head(2)
#df.tail(2)
#df.info()
print(df.head(2))
print(df.tail(2))
print(df.info())
print(df.shape)
dup_df= pd.concat([df,df])
print(dup_df.shape)
dup_dff=dup_df.drop_duplicates()
print(dup_dff.shape)
print(df.describe())